" $XDG_CONFIG_HOME/vim/vimrc
" need  < alias vim='vim -u $XDG_CONFIG_HOME/vim/vimrc > in zsh.rc to read this file
" Last modified 2014-01-29


" use LanguageTool plugin
set nocompatible
filetype plugin on

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set autoindent		" always set autoindenting on
set number

" defaults for tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

" set up languagetool_jar
"let g:languagetool_jar=$HOME . 'usr/share/java/languagetool/LanguageTool.jar'

set encoding=utf-8
set fileencoding=utf-8
set t_co=256		" enable 256 colors "

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" For all text files set 'textwidth' to 78 characters.
autocmd FileType text setlocal textwidth=78

" choose color theme
colorscheme mustang