" $XDG_CONFIG_HOME/vim/vimrc  @ hortensia
" need  < alias vim='vim -u $XDG_CONFIG_HOME/vim/vimrc > in zsh.rc to read this file
" Last modified 2018-08-10


" Use Vim settings. This must be first
set nocompatible
filetype off " required by Vundle

" allow file format detection and plugin use
syntax enable
filetype plugin on
filetype indent on

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/vim/bundle/Vundle.vim
call vundle#begin()
" call vundle#begin(~/.config/vim/bundle/Vundle.vim)
" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'
" add all plugins here 
" format for git : user/repository
" to install, place below plugin then run vim, :PluginUpdate
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'rstacruz/sparkup'
Plugin 'bling/vim-airline'
Plugin 'plasticboy/vim-markdown'
Plugin 'Yggdroot/indentLine'
Plugin 'Mustang2'
Plugin 'justb3a/vim-smarties'
Plugin 'xmledit'
Plugin 'chriskempson/base16-vim'

"!!!!!!!!!!!!!!!!!!!!!!!
" Plugin '
" all plugins must be added before this line

call vundle#end() "required
" turn filetype functionality back on
filetype plugin indent on "required

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Basic settings
set viminfo+=n~/.config/vim/viminfo
set history=500		" keep 100 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set autoindent		" always set autoindenting on
set smartindent	
set showcmd		" display incomplete commands
set showmatch		" highlight matching braces/brackets	
set number		" turns line numbering on
set showmode
set laststatus=2	" always show status line
set display+=lastline
set linebreak
set title
set encoding=utf-8
set fileencoding=utf-8
set t_co=256		" enable 256 colors 
set tabstop=4		" defaults indent to 4 spaces for tabs 
set shiftwidth=4
set softtabstop=4
set mouse=a		" enable mouse
set mousehide 		" hide when characters are typed
set nobackup		" turn backup off
set nowritebackup

" tmux support
let g:ScreenImpl = 'Tmux'
let g:ScreenShellInitialFocus = 'shell' 
" latex stuff
" For Latex work: open *.pdf files in evince/xpdf upon opening of *.tex files in vim 
au BufRead *.tex silent !xpdf %<.pdf 2>/dev/null &
au BufRead *.Rnw silent !xpdf %<.pdf 2>/dev/null &

" file type sepcific commands
" For all text files set 'textwidth' to 78 characters.
autocmd FileType text setlocal textwidth=78
" override default tab to 4 spaces
autocmd FileType html setlocal ts=2 sw=2 expandtab
" set up languagetool_jar
"let g:languagetool_jar=$HOME . 'usr/share/java/languagetool/LanguageTool.jar'



" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" indent line color
let g:indentLine_color_term = 239
let g:html_indent_inctags = "html,body,head,tbody"
" choose color theme
" colo mustang

" Jump back to the last edit position when opening a file
:au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif



