#!/bin/bash

# Script to backup personal files to the external USB drive.
# /etc/scripts/cron_backup @ hortensia
# Last edited 2014-08-13

now=`date +"%m_%d_%Y"`
BKLOG=/mnt/error_$now.txt
touch $BKLOG
PACBAK=/backup/pacman/lib/local


# Log everything to log file
exec &>> $BKLOG

echo -e "Subject: weekly backup logs\n"

# define mount point
MP=/mnt/backup

# create mount point if does not exist
if [ ! -d $MP ]; then
	mkdir /mnt/backup
fi 

# mount backup drive if not already mounted
if ! mountpoint -q $MP; then
	mount /dev/vg1/backup_external $MP
fi


# backup directory path
BKHO=$MP/hortensia
#BKDA=$MP/dahlia


# exclude file
EXCLHO=/etc/conf.d/exclude-hortensia
#EXCLDA=/etc/conf.d/exclude-dahlia

echo -e "\nRUNNING RSYNC\n" 

# backup host
# use rsync for backup
# usage rsync source destination --exclude
rsync -av --delete /* $BKHO --exclude-from $EXCLHO


# backup container
#START=$(date +%s)
#rsync -av --delete /var/lib/container/dahlia/* $BKDA --exclude-from $EXCLDA
#FINISH=$(date +%s)
#echo "total time: $(( ($FINISH-$START) / 60 )) minutes, $(( ($FINISH-$START) % 60 )) seconds" | tee $BKDA/"Backup_dahlia_from $(date '+%A, %d %B %Y, %T')"



# some pacman stuff
pacman -Qen > $BKHO/pkglist_$now.txt
tar -cJf $BKHO/pacDB_$now.tar.xz $PACBAK 

echo -e "\nRUNNIG SYSTEMCTL --FAILED\n" 
systemctl --failed 

echo -e "\nRUNNING SYSTEMCTL LIST-TIMERS\n" 
systemctl list-timers


# send email
cat $BKLOG | msmtp -a default arnaud.gaboury@gmail.com 


# remove log if nothing failed
if [ $? = 0 ]; then 
	rm /mnt/error*
fi

# remove files to cleanup
rm $BKHO/pkglist*

# unmount backup drive
umount /mnt/backup





